### ISSUE TITLE
url for the repo

### ISSUE THREAD

**Issue by jaktk** [Global-Health-Engineering/zurichwastecollection#1]
@larnsce, do we get the url in the citation file for the repo? Dominic needs to be able to cite it and I'd like it to be easily trackable. Can I add https://github.com/Global-Health-Engineering/zurichwastecollection as the url entry? Will it stay as such forever?

**Comment by larnsce** [comment]
@jaktk, yes you can add it. We typically only show the DOI to Zenodo and then from there the website link. Dominic's repo and Zenodo site are currently only WIP/MVP because he needed the actual citation for his thesis. This would cover it. 

Once he has submitted his thesis, we will turn the repo into a website and also update the Zenodo entry. 

Here is what I shared with him via email:

Referenz (in APA):

Wälti, D., Tilley, E., Tkaczuk, J., & Schöbitz, L. (2023). zurichwastecollection: Zurich (Switzerland) Waste Collection Data (v0.0.0.9000). Zenodo. https://doi.org/10.5281/zenodo.10039803Wälti, D., Tilley, E., Tkaczuk, J., & Schöbitz, L. (2023). zurichwastecollection: Zurich (Switzerland) Waste Collection Data (v0.0.0.9000). Zenodo. https://doi.org/10.5281/zenodo.10039803

BibTeX (already in Zotero)

https://www.zotero.org/groups/4445072/global_health_engineering/collections/6UEP3T33

**Comment by jaktk** [comment]
Great, thank you Lars, I must have misunderstood the problem.
